name: Build conduit binaries
on: [push]
jobs:
  buildConduit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        dc: [ldc]
        include:
          - { os: macos-13, dc: dmd }
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
      - name: Build
        run: dub build -b release
      - name: Release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: conduit-${{runner.os}}-${{runner.arch}}
          path: ./conduit
  buildConduitWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc
      - name: Build
        run: dub build -b release
      - name: Release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: conduit.exe
          path: ./conduit.exe

